/**
 * Biblioteca expandida — acervo Everkinetic (domínio público), composto
 * início→contração por exercício. Gerado por script (não editar à mão).
 */
import type { DemoCategory, DemoExercise } from "./demo-data";

const evkEx = (idNum: string, name: string, info: string): DemoExercise => ({
  id: `evk-${idNum}`,
  name,
  picto: "acervo",
  info,
  equipment: null,
  tags: ["acervo"],
  imageUrl: `https://jeixbpucnxrhizqpapyv.supabase.co/storage/v1/object/public/exercise-images/evk-${idNum}.webp?v=2`,
  thumbUrl: `https://jeixbpucnxrhizqpapyv.supabase.co/storage/v1/object/public/exercise-images/evk-${idNum}.webp?v=2`,
  videoUrl: `https://www.youtube.com/results?search_query=${encodeURIComponent(name + " execução")}`,
  videoUrlMale: null,
  videoUrlFemale: null,
});

export const EXPANDED_SUBS: Array<{ catId: string; sub: DemoCategory["subs"][number] }> = [
  {
    catId: "abdomen",
    sub: {
      id: "abdomen-acervo",
      name: "Abdômen · acervo completo",
      exercises: [
        evkEx("0027", "Stationary Abdominal Draw In", "Exercício para Abdômen, execução controlada e cadência constante."),
        evkEx("0284", "Air Bike", "Exercício para Abdômen, execução controlada e cadência constante."),
        evkEx("0285", "Ab Rollout with Barbell", "Exercício para Abdômen, execução controlada e cadência constante."),
        evkEx("0286", "Ab Rollout on Knees with Barbell", "Exercício para Abdômen, execução controlada e cadência constante."),
        evkEx("0287", "Bent Knee Hip Raise", "Exercício para Abdômen, execução controlada e cadência constante."),
        evkEx("0289", "Cross Body Crunch", "Exercício para Abdômen, execução controlada e cadência constante."),
        evkEx("0290", "Crunches with Legs on Stability Ball", "Exercício para Abdômen, execução controlada e cadência constante."),
        evkEx("0292", "Decline Crunch", "Exercício para Abdômen, execução controlada e cadência constante."),
        evkEx("0293", "Decline Oblique Crunch", "Exercício para Abdômen, execução controlada e cadência constante."),
        evkEx("0294", "Side Bend with Dumbbell", "Exercício para Abdômen, execução controlada e cadência constante."),
        evkEx("0295", "Stability Ball Abdominal Crunch", "Exercício para Abdômen, execução controlada e cadência constante."),
        evkEx("0296", "Exercise Ball Pull In", "Exercício para Abdômen, execução controlada e cadência constante."),
      ],
    },
  },
  {
    catId: "biceps",
    sub: {
      id: "biceps-acervo",
      name: "Bíceps · acervo completo",
      exercises: [
        evkEx("0214", "Alternating Incline Curl with Dumbbell", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0215", "Lying Incline Curl with Barbell", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0216", "Hammer Curls with Rope and Cable", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0217", "Preacher Curl with Cable", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0218", "Close Grip EZ Bar Curl with Barbell", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0219", "Close Grip Standing Biceps Curls with Barbell", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0221", "Cross Body Hammer Curl with Dumbbell", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0222", "Drag Curl with Barbell", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0224", "Biceps Curl with Dumbbell", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0225", "Prone Incline Biceps Curl with Dumbbell", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0226", "EZ Bar Curl with Barbell", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0227", "Biceps Hammer Curl with Dumbbell", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0228", "Flexor Incline Curls with Dumbbell", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0229", "High Cable Curls", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0231", "Incline Inner Biceps Curl with Dumbbell", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0232", "Lying Bicep Cable Curl", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0233", "Lying Close Grip Biceps Curls with Cable", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0234", "Lying High Bench Biceps Curl with Barbell", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0235", "Lying Supine Biceps Curl with Dumbbell", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0236", "Preacher Curl with Machine", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0237", "One Arm Preacher Curl with Dumbbell", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0238", "Overhead Curl with Cable", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0240", "Preacher Hammer Curl with Dumbbell", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0241", "Reverse Plate Curls with Weight", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0242", "Seated Close Grip Concentration Curls with Barbell", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0243", "Seated Bicep Curl with Dumbbell", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0245", "Spider Curl with Barbell", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0246", "Standing Inner Biceps Curl with Dumbbell", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0247", "Standing One Arm Bicep Curl with Cable", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0248", "Standing One Arm Curl Over Incline Bench with Dumbbell", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0249", "Two-Arm Preacher Curl with Dumbbell", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0250", "Wide Grip Standing Biceps Curl with Barbell", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0251", "Zottman Curl with Dumbbells", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0252", "Zottman Preacher Curl with Dumbbells", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0253", "Bicep Curl with Machine", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0254", "One Arm Bicep Curl with Olympic Bar or Barbell", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0255", "Biceps Curl Seated on Stability Ball with Dumbbell", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0256", "Biceps Curl Squat with Dumbbell", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0258", "One Arm Bicep Concentration on Stability Ball with Dumbbell", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0259", "Bicep Curl with Deadlift with Barbell", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0260", "Biceps Curl with Overhead Extension using Dumbbells on Stability Ball", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0262", "Bicep Curl Lunge with Bowling Motion", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0263", "Bicep Curl on Stability Ball with Leg Raised", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0265", "Forward Lunge with Bicep Curl using Dumbbell", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0267", "Medicine Ball Biceps Curl on Stability Ball", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0268", "Stork Stance Bicep Curl with Dumbbells", "Exercício para Bíceps, execução controlada e cadência constante."),
        evkEx("0269", "Biceps Curl V Sit on Dome with Dumbbells", "Exercício para Bíceps, execução controlada e cadência constante."),
      ],
    },
  },
  {
    catId: "costas",
    sub: {
      id: "costas-acervo",
      name: "Costas · acervo completo",
      exercises: [
        evkEx("0091", "Wide Grip Chin Up", "Exercício para Costas, execução controlada e cadência constante."),
      ],
    },
  },
  {
    catId: "inferiores",
    sub: {
      id: "inferiores-acervo",
      name: "Pernas · acervo completo",
      exercises: [
        evkEx("0111", "Body Leg Lifts", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0115", "Dumbbell Lunges", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0116", "Flutter Kicks", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0120", "Standing Leg Curls", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0123", "Hack Squat Machine", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0125", "Hack Squat with barbell", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0126", "Smith Machine Hack Squat", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0128", "Rear Lunges with Barbell", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0129", "Rear Lunges with Dumbbell", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0130", "Squats using Dumbbells", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0131", "Side Squats with Barbell", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0133", "Squat to Bench with Barbell", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0134", "Step Ups with Barbell", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0135", "Hip Adduction", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0136", "Squat to Bench with Dumbbells", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0137", "Step Ups with Dumbbells", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0139", "Front Squat to Bench with Barbells", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0140", "Iron Cross with Dumbbells", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0141", "Jefferson Squats with Barbell", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0143", "Narrow Stance Leg Press", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0144", "Lying Squat", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0145", "Narrow Stance Hack Squats", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0146", "Narrow Stance Squat with Barbell", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0147", "One Leg Squat with Barbell", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0148", "One Arm Snatch with Barbell", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0150", "One Arm Side Deadlift with Barbell", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0151", "Overhead Squat with Barbell", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0154", "Speed Squats with Barbell", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0157", "Thigh Adductor", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0158", "Weighted Sissy Squat with Weight Plate", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0160", "Wide Stance Squat with Barbell", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0161", "Zecher Squats", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0264", "Lateral Lunge with Bicep Curl with Dumbbell", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0270", "Ankle Circles", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0275", "Donkey Calf Raises", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0276", "Seated One Leg Calf Raise with Dumbbell", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0277", "Knee Circles", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0278", "Rocking Standing Calf Raise with Barbell", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0279", "Seated Calf Raise using Machine", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0280", "Smith Machine Reverse Calf Raises", "Exercício para Pernas, execução controlada e cadência constante."),
        evkEx("0282", "Standing Calf Raises using Machine", "Exercício para Pernas, execução controlada e cadência constante."),
      ],
    },
  },
  {
    catId: "ombro",
    sub: {
      id: "ombro-acervo",
      name: "Ombros · acervo completo",
      exercises: [
        evkEx("0008", "Front Cable Raises", "Exercício para Ombros, execução controlada e cadência constante."),
        evkEx("0013", "Smith Machine Upright Row", "Exercício para Ombros, execução controlada e cadência constante."),
        evkEx("0014", "Upright Barbell Rows", "Exercício para Ombros, execução controlada e cadência constante."),
        evkEx("0015", "Upright Cable Row", "Exercício para Ombros, execução controlada e cadência constante."),
        evkEx("0016", "Dumbbell Upright Rows", "Exercício para Ombros, execução controlada e cadência constante."),
        evkEx("0019", "Ball Wall Circles", "Exercício para Ombros, execução controlada e cadência constante."),
        evkEx("0022", "Smith Machine Rear Deltoid Row", "Exercício para Ombros, execução controlada e cadência constante."),
        evkEx("0023", "Lying Rear Lateral Raise", "Exercício para Ombros, execução controlada e cadência constante."),
        evkEx("0028", "Rear Deltoid Row Barbell", "Exercício para Ombros, execução controlada e cadência constante."),
        evkEx("0032", "Bent Over Rear Deltoid Raise With Head On Bench", "Exercício para Ombros, execução controlada e cadência constante."),
        evkEx("0034", "Internal Cable Rotation", "Exercício para Ombros, execução controlada e cadência constante."),
        evkEx("0035", "Seated Rear Lateral Cable Raise", "Exercício para Ombros, execução controlada e cadência constante."),
        evkEx("0037", "Lying One Arm Rear Lateral Raise", "Exercício para Ombros, execução controlada e cadência constante."),
        evkEx("0039", "One Arm Upright Row", "Exercício para Ombros, execução controlada e cadência constante."),
        evkEx("0041", "Smith Machine Shoulder Shrugs", "Exercício para Ombros, execução controlada e cadência constante."),
        evkEx("0090", "Narrow Parallel Grip Chin-ups", "Exercício para Ombros, execução controlada e cadência constante."),
        evkEx("0098", "Pullover On Stability Ball With Weight", "Exercício para Ombros, execução controlada e cadência constante."),
      ],
    },
  },
  {
    catId: "peito",
    sub: {
      id: "peito-acervo",
      name: "Peito · acervo completo",
      exercises: [
        evkEx("0045", "Bent Arm Pullover", "Exercício para Peito, execução controlada e cadência constante."),
        evkEx("0046", "Dumbbell Bent Arm Pullover", "Exercício para Peito, execução controlada e cadência constante."),
        evkEx("0049", "Close Grip Barbell Bench Press", "Exercício para Peito, execução controlada e cadência constante."),
        evkEx("0052", "Decline Dumbbell Bench Press", "Exercício para Peito, execução controlada e cadência constante."),
        evkEx("0053", "Decline Dumbbell Fly's", "Exercício para Peito, execução controlada e cadência constante."),
        evkEx("0058", "Barbell Front Raise and Pullover", "Exercício para Peito, execução controlada e cadência constante."),
        evkEx("0059", "Hammer Grip Incline Bench Press", "Exercício para Peito, execução controlada e cadência constante."),
        evkEx("0060", "Incline Cable Fly's", "Exercício para Peito, execução controlada e cadência constante."),
        evkEx("0061", "Dumbbell Incline Bench Press", "Exercício para Peito, execução controlada e cadência constante."),
        evkEx("0062", "Incline Dumbbell Fly's", "Exercício para Peito, execução controlada e cadência constante."),
        evkEx("0063", "Incline Fly's with a Twist", "Exercício para Peito, execução controlada e cadência constante."),
        evkEx("0064", "Wide Grip Decline Barbell Pullover", "Exercício para Peito, execução controlada e cadência constante."),
        evkEx("0066", "Machine Bench Press", "Exercício para Peito, execução controlada e cadência constante."),
        evkEx("0068", "One Arm Bench Press", "Exercício para Peito, execução controlada e cadência constante."),
        evkEx("0069", "Bosu Ball Push Up", "Exercício para Peito, execução controlada e cadência constante."),
        evkEx("0070", "One Arm Barbell Floor Press", "Exercício para Peito, execução controlada e cadência constante."),
        evkEx("0071", "One Arm Flat Bench Fly’s", "Exercício para Peito, execução controlada e cadência constante."),
        evkEx("0072", "One Armed Biased Push Up", "Exercício para Peito, execução controlada e cadência constante."),
        evkEx("0076", "Push Ups with feet on exercise ball", "Exercício para Peito, execução controlada e cadência constante."),
        evkEx("0079", "Straight Arm Dumbbell Pullover", "Exercício para Peito, execução controlada e cadência constante."),
        evkEx("0080", "Incline Dumbbell Press", "Exercício para Peito, execução controlada e cadência constante."),
        evkEx("0081", "Smith Machine Incline Bench Press", "Exercício para Peito, execução controlada e cadência constante."),
        evkEx("0082", "Wide Grip Bench Press", "Exercício para Peito, execução controlada e cadência constante."),
        evkEx("0083", "Wide Grip Decline Bench Press", "Exercício para Peito, execução controlada e cadência constante."),
        evkEx("0085", "Decline Chest Press", "Exercício para Peito, execução controlada e cadência constante."),
        evkEx("0086", "Body Row", "Exercício para Peito, execução controlada e cadência constante."),
      ],
    },
  },
  {
    catId: "triceps",
    sub: {
      id: "triceps-acervo",
      name: "Tríceps · acervo completo",
      exercises: [
        evkEx("0020", "Tate Press", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0162", "Bench Dips", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0163", "Incline Pushdown with Cable", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0164", "Incline Triceps Extension with Cable", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0165", "Lying Tricep Extension with Cable", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0166", "One Arm Tricep Extension with Cable", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0168", "Decline Close Grip Bench to Skull Crusher", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0169", "Decline Triceps Extension with Dumbbell", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0170", "Decline EZ Bar Triceps Extension with Barbell", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0171", "Tricep Dips using Machine", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0173", "One Arm Triceps Extension with Dumbbell", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0174", "Incline Triceps Extension with Barbell", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0175", "JM Press", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0176", "Kneeling Triceps Concentration Extension with Cable", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0177", "Kneeling Triceps Extension with Cable", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0178", "Low Triceps Extension with Cable", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0180", "Lying Close Grip Triceps Press to Chin with Barbell", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0181", "Lying Triceps Extension with Dumbbells", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0182", "Lying Triceps Extension Across Face with Dumbbell", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0183", "Lying Triceps Press with Barbell", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0184", "Lying Two Arm Triceps Extension with Dumbbell", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0185", "Old School Reverse Extensions", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0186", "Single Arm Pronated Triceps Extension with Dumbbell", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0187", "Single Arm Supinated Triceps Extension with Dumbbell", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0188", "Close Triceps Pushup", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0189", "Reverse Grip Triceps Pushdown", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0190", "Reverse Triceps Bench Press with Barbell", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0191", "Seated One Arm Triceps Extension with Dumbbell", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0192", "Seated Two-Arm Triceps Extension with Dumbbell", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0194", "Seated Triceps Press with Dumbbell", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0195", "Smith Machine Close Grip Bench Press", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0196", "Bent-Over One Arm Triceps Extension with Dumbbell", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0197", "Bent-Over Two Arm Triceps Extension with Dumbbell", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0198", "Standing Triceps Extension", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0199", "One Arm Low-Pulley Triceps Extension with Cable", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0201", "Standing Overhead Triceps Extension with Barbell", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0202", "Standing Triceps Extension with Towel", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0203", "Tate Press with Dumbbell", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0204", "Triceps Kickback with Dumbbell", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0207", "Triceps Pushdown with V Bar and Cable", "Exercício para Tríceps, execução controlada e cadência constante."),
        evkEx("0209", "Incline Triceps Extensions with Dumbbell", "Exercício para Tríceps, execução controlada e cadência constante."),
      ],
    },
  },
];

/** Anexa os subs expandidos às categorias do demoLib (in place). */
export function applyExpandedLibrary(demoLib: DemoCategory[]): void {
  for (const { catId, sub } of EXPANDED_SUBS) {
    const cat = demoLib.find((c) => c.id === catId);
    if (cat) cat.subs.push(sub);
  }
}
