/**
 * Biblioteca expandida · acervo Everkinetic (domínio público), composto
 * início→contração por exercício. Gerado por script (não editar à mão).
 */
import type { DemoCategory, DemoExercise } from "./demo-data";

const evkEx = (idNum: string, name: string, equip: string | null, info: string): DemoExercise => ({
  id: `evk-${idNum}`,
  name,
  picto: "acervo",
  info,
  equipment: equip,
  tags: ["acervo"],
  imageUrl: `https://jeixbpucnxrhizqpapyv.supabase.co/storage/v1/object/public/exercise-images/evk-${idNum}.webp?v=2`,
  thumbUrl: `https://jeixbpucnxrhizqpapyv.supabase.co/storage/v1/object/public/exercise-images/evk-${idNum}.webp?v=2`,
  videoUrl: `https://www.youtube.com/results?search_query=${encodeURIComponent(name + " execução")}`,
  videoUrlMale: null,
  videoUrlFemale: null,
});

export const EXPANDED_SUBS: Array<{ catId: string; sub: DemoCategory["subs"][number] }> = [
  {
    catId: "abdomen",
    sub: {
      id: "abdomen-acervo",
      name: "Acervo completo",
      exercises: [
        evkEx("0027", "Abdominal Draw In", "Peso corporal", "Foco em abdômen · Peso corporal. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0284", "Bicicleta Air Bike", "Peso corporal", "Foco em abdômen · Peso corporal. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0285", "Ab Rollout com Barra", "Barra", "Foco em abdômen · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0286", "Ab Rollout de Joelhos com Barra", "Barra", "Foco em abdômen · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0287", "Elevação de Quadril com Joelhos Dobrados", "Peso corporal", "Foco em abdômen · Peso corporal. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0289", "Abdominal Cruzado", "Peso corporal", "Foco em abdômen · Peso corporal. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0290", "Abdominal com Pés na Bola", "Bola", "Foco em abdômen · Bola. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0292", "Abdominal Declinado", "Peso corporal", "Foco em abdômen · Peso corporal. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0293", "Abdominal Oblíquo Declinado", "Peso corporal", "Foco em abdômen · Peso corporal. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0294", "Flexão Lateral com Halter", "Halteres", "Foco em abdômen · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0295", "Abdominal na Bola", "Peso corporal", "Foco em abdômen · Peso corporal. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0296", "Abdominal com Bola", "Peso corporal", "Foco em abdômen · Peso corporal. Execução controlada, descida em 2 a 3 segundos."),
      ],
    },
  },
  {
    catId: "biceps",
    sub: {
      id: "biceps-acervo",
      name: "Acervo completo",
      exercises: [
        evkEx("0214", "Rosca Inclinada Alternada com Halteres", "Halteres", "Foco em bíceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0215", "Rosca Inclinada com Barra", "Barra", "Foco em bíceps · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0216", "Rosca Martelo na Corda", "Cabo", "Foco em bíceps · Cabo. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0217", "Rosca Scott no Cabo", "Cabo", "Foco em bíceps · Cabo. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0218", "Close Grip Rosca Direta com Barra W", "Barra", "Foco em bíceps · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0219", "Close Grip Standing Rosca Direta com Barra", "Barra", "Foco em bíceps · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0221", "Rosca Martelo Cruzada com Halter", "Halteres", "Foco em bíceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0222", "Rosca Drag", "Barra", "Foco em bíceps · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0224", "Rosca Direta com Halteres", "Halteres", "Foco em bíceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0225", "Prone Incline Rosca Direta com Halteres", "Halteres", "Foco em bíceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0226", "Rosca Direta com Barra W", "Barra", "Foco em bíceps · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0227", "Rosca Martelo com Halteres", "Halteres", "Foco em bíceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0228", "Rosca Inclinada Flexora com Halteres", "Halteres", "Foco em bíceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0229", "Rosca Alta no Cabo", "Cabo", "Foco em bíceps · Cabo. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0231", "Incline Inner Rosca Direta com Halteres", "Halteres", "Foco em bíceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0232", "Rosca Deitado no Cabo", "Cabo", "Foco em bíceps · Cabo. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0233", "Rosca Deitada Pegada Fechada no Cabo", "Cabo", "Foco em bíceps · Cabo. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0234", "Rosca no Banco Alto com Barra", "Barra", "Foco em bíceps · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0235", "Lying Supine Rosca Direta com Halteres", "Halteres", "Foco em bíceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0236", "Rosca Scott na Máquina", "Máquina", "Foco em bíceps · Máquina. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0237", "Rosca Scott Unilateral com Halter", "Halteres", "Foco em bíceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0238", "Rosca Acima da Cabeça no Cabo", "Cabo", "Foco em bíceps · Cabo. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0240", "Rosca Scott Martelo com Halteres", "Halteres", "Foco em bíceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0241", "Rosca Inversa com Anilha", "Weight plate", "Foco em bíceps · Weight plate. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0242", "Rosca Concentrada Pegada Fechada", "Barra", "Foco em bíceps · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0243", "Rosca Sentado com Halteres", "Halteres", "Foco em bíceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0245", "Rosca Spider com Barra", "Barra", "Foco em bíceps · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0246", "Standing Inner Rosca Direta com Halteres", "Halteres", "Foco em bíceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0247", "Rosca Unilateral no Cabo", "Cabo", "Foco em bíceps · Cabo. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0248", "Rosca Unilateral no Banco Inclinado", "Halteres", "Foco em bíceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0249", "Rosca Scott com Halteres", "Halteres", "Foco em bíceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0250", "Rosca Direta Pegada Aberta", "Barra", "Foco em bíceps · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0251", "Rosca Zottman com Halteres", "Halteres", "Foco em bíceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0252", "Rosca Zottman Scott com Halteres", "Halteres", "Foco em bíceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0253", "Rosca na Máquina", null, "Foco em bíceps. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0254", "Rosca Unilateral com Barra Olímpica", "Barra", "Foco em bíceps · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0255", "Rosca Sentado na Bola com Halteres", "Halteres", "Foco em bíceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0256", "Rosca no Agachamento com Halter", "Halteres", "Foco em bíceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0258", "One Arm Bicep Concentration na Stability Ball com Dumbbell", "Halteres", "Foco em bíceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0259", "Rosca com Levantamento Terra", "Barra", "Foco em bíceps · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0260", "Rosca com Extensão na Bola", "Halteres", "Foco em bíceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0262", "Afundo com Rosca", "Bola de medicine", "Foco em bíceps · Bola de medicine. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0263", "Rosca na Bola com Perna Elevada", "Halteres", "Foco em bíceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0265", "Afundo Frontal com Rosca", "Halteres", "Foco em bíceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0267", "Rosca com Medicine Ball na Bola", "Bola de medicine", "Foco em bíceps · Bola de medicine. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0268", "Rosca Equilíbrio Unipodal com Halteres", "Halteres", "Foco em bíceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0269", "Rosca em V no Bosu com Halteres", "Halteres", "Foco em bíceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
      ],
    },
  },
  {
    catId: "costas",
    sub: {
      id: "costas-acervo",
      name: "Acervo completo",
      exercises: [
        evkEx("0091", "Barra Fixa Pegada Aberta Supinada", null, "Foco em costas. Execução controlada, descida em 2 a 3 segundos."),
      
        evkEx("0045", "Pullover (Dorsal)", "Barra", "Foco em costas · Barra. Braços quase estendidos, foque no dorsal."),
        evkEx("0092", "Pulldown Braços Estendidos", "Máquina", "Foco em costas · Máquina. Braços estendidos, puxe com o dorsal."),
        evkEx("0099", "Levantamento Terra com Barra", "Barra", "Foco em costas · Barra. Coluna neutra, suba com os quadris e as pernas."),
        evkEx("0105", "Superman (Costas)", "Peso corporal", "Foco em costas · Peso corporal. Isometria de 2 a 3 segundos no topo."),
        evkEx("0086", "Remada Invertida", "Peso corporal", "Foco em costas · Peso corporal. Corpo alinhado, puxe o peito até a barra."),
        evkEx("0014", "Remada Alta com Barra", "Barra", "Foco em costas · Barra. Cotovelos altos, barra junto ao corpo."),

        evkEx("0107", "Levantamento Terra com Halteres", "Halteres", "Foco em costas · Halteres. Coluna neutra, quadril para trás."),
        evkEx("0046", "Pullover Cotovelos Flexionados com Halteres", "Halteres", "Foco em costas · Halteres. Arco completo, foque no dorsal."),
        evkEx("0079", "Pullover Braços Estendidos com Halteres", "Halteres", "Foco em costas · Halteres. Braços quase estendidos, arco amplo."),
        evkEx("0098", "Pullover na Bola com Carga", "Bola", "Foco em costas · Bola. Estabilize o core durante o arco."),
],   },
  },
  {
    catId: "inferiores",
    sub: {
      id: "inferiores-acervo",
      name: "Acervo completo",
      exercises: [
        evkEx("0111", "Elevação de Pernas no Solo", "Peso corporal", "Foco em pernas · Peso corporal. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0115", "Afundo com Halteres", "Dumbbells", "Foco em pernas · Dumbbells. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0116", "Flutter Kicks", "Banco reto", "Foco em pernas · Banco reto. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0120", "Flexora em Pé", "Máquina", "Foco em pernas · Máquina. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0123", "Agachamento Hack na Máquina", "Máquina", "Foco em pernas · Máquina. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0125", "Agachamento Hack com Barra", "Barra", "Foco em pernas · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0126", "Agachamento Hack no Smith", "Smith machine", "Foco em pernas · Smith machine. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0128", "Afundo Traseiro com Barra", "Barra", "Foco em pernas · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0129", "Afundo Traseiro com Halteres", "Dumbbells", "Foco em pernas · Dumbbells. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0130", "Agachamento com Halteres", "Dumbbells", "Foco em pernas · Dumbbells. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0131", "Agachamento Lateral com Barra", "Barra", "Foco em pernas · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0133", "Agachamento no Banco com Barra", "Barra", "Foco em pernas · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0134", "Step Up com Barra", "Barra", "Foco em pernas · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0135", "Adução de Quadril", "Cabo", "Foco em pernas · Cabo. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0136", "Agachamento no Banco com Halteres", "Halteres", "Foco em pernas · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0137", "Step Up com Halteres", "Dumbbells", "Foco em pernas · Dumbbells. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0139", "Agachamento Frontal no Banco", "Barra", "Foco em pernas · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0140", "Iron Cross com Dumbbells", "Dumbbells", "Foco em pernas · Dumbbells. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0141", "Jefferson Squats com Barbell", "Barra", "Foco em pernas · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0143", "Leg Press Pegada Fechada", "Máquina", "Foco em pernas · Máquina. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0144", "Agachamento Deitado", "Máquina", "Foco em pernas · Máquina. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0145", "Agachamento Hack Pegada Fechada", "Máquina", "Foco em pernas · Máquina. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0146", "Agachamento Fechado com Barra", "Barra", "Foco em pernas · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0147", "One Leg Squat com Barbell", "Barra", "Foco em pernas · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0148", "Arranco Unilateral com Barra", "Barra", "Foco em pernas · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0150", "Levantamento Terra Unilateral com Barra", "Barra", "Foco em pernas · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0151", "Agachamento Acima da Cabeça com Barra", "Barra", "Foco em pernas · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0154", "Agachamento Velocidade com Barra", "Barra", "Foco em pernas · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0157", "Cadeira Adutora", "Máquina", "Foco em pernas · Máquina. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0158", "Agachamento Sissy com Anilha", "Weight plate", "Foco em pernas · Weight plate. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0160", "Agachamento Pegada Larga com Barra", "Barra", "Foco em pernas · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0161", "Agachamento Zecher", "Barra", "Foco em pernas · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0264", "Afundo Lateral com Rosca", "Halteres", "Foco em pernas · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0270", "Círculos com o Tornozelo", "Peso corporal", "Foco em pernas · Peso corporal. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0275", "Panturrilha Burro", "Peso corporal", "Foco em pernas · Peso corporal. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0276", "Panturrilha Sentado Unilateral com Halter", "Halteres", "Foco em pernas · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0277", "Círculos com o Joelho", "Peso corporal", "Foco em pernas · Peso corporal. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0278", "Panturrilha em Pé com Barra", "Barra", "Foco em pernas · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0279", "Panturrilha Sentado na Máquina", "Máquina", "Foco em pernas · Máquina. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0280", "Panturrilha Reversa no Smith", "Smith machine", "Foco em pernas · Smith machine. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0282", "Panturrilha em Pé na Máquina", "Máquina", "Foco em pernas · Máquina. Execução controlada, descida em 2 a 3 segundos."),
      ],
    },
  },
  {
    catId: "ombro",
    sub: {
      id: "ombro-acervo",
      name: "Acervo completo",
      exercises: [
        evkEx("0008", "Elevação Frontal no Cabo", "Cable machine", "Foco em ombros · Cable machine. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0013", "Remada Alta no Smith", "Smith machine", "Foco em ombros · Smith machine. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0014", "Remada Alta com Barra", "Barra", "Foco em ombros · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0015", "Remada Alta no Cabo", "Cable machine", "Foco em ombros · Cable machine. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0016", "Remada Alta com Halteres", "Dumbbells", "Foco em ombros · Dumbbells. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0019", "Círculos na Parede com Bola", "Swiss ball", "Foco em ombros · Swiss ball. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0022", "Remada Posterior no Smith", "Smith machine", "Foco em ombros · Smith machine. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0023", "Elevação Posterior Deitado", "Banco reto / dumbbells", "Foco em ombros · Banco reto / dumbbells. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0028", "Remada Posterior com Barra", "Barra", "Foco em ombros · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0032", "Elevação Posterior com Cabeça no Banco", "Dumbbells", "Foco em ombros · Dumbbells. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0034", "Rotação Interna no Cabo", "Cable machine", "Foco em ombros · Cable machine. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0035", "Elevação Posterior no Cabo", "Cable machine", "Foco em ombros · Cable machine. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0037", "Elevação Posterior Unilateral", "Halteres / banco reto", "Foco em ombros · Halteres / banco reto. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0039", "Remada Alta Unilateral", "Halteres", "Foco em ombros · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0041", "Smith Máquina Encolhimento de Ombros", "Smith machine", "Foco em ombros · Smith machine. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0090", "Barra Fixa Pegada Neutra", "Barra / peso corporal", "Foco em ombros · Barra / peso corporal. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0098", "Pullover na Bola com Carga", "Bola / halteres", "Foco em ombros · Bola / halteres. Execução controlada, descida em 2 a 3 segundos."),
      ],
    },
  },
  {
    catId: "peito",
    sub: {
      id: "peito-acervo",
      name: "Acervo completo",
      exercises: [
        evkEx("0045", "Pullover com Cotovelos Flexionados", "Barra / banco reto", "Foco em peito · Barra / banco reto. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0046", "Dumbbell Pullover com Cotovelos Flexionados", "Banco reto / halteres", "Foco em peito · Banco reto / halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0049", "Close Grip Barbell Supino Reto", "Barra", "Foco em peito · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0052", "Decline Dumbbell Supino Reto", "Dumbbells / banco declinado", "Foco em peito · Dumbbells / banco declinado. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0053", "Decline Crucifixo com Halteres", "Dumbbells / banco declinado", "Foco em peito · Dumbbells / banco declinado. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0058", "Elevação Frontal com Pullover", "Barra / banco reto", "Foco em peito · Barra / banco reto. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0059", "Hammer Grip Incline Supino Reto", "Dumbbells / banco inclinado", "Foco em peito · Dumbbells / banco inclinado. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0060", "Crucifixo Inclinado no Cabo", "Banco inclinado / cable machine", "Foco em peito · Banco inclinado / cable machine. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0061", "Dumbbell Incline Supino Reto", "Dumbbells / banco inclinado", "Foco em peito · Dumbbells / banco inclinado. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0062", "Incline Crucifixo com Halteres", "Banco inclinado / dumbbells", "Foco em peito · Banco inclinado / dumbbells. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0063", "Crucifixo Inclinado com Rotação", "Banco inclinado / dumbbells", "Foco em peito · Banco inclinado / dumbbells. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0064", "Pullover Declinado Pegada Aberta", "Banco declinado / barra", "Foco em peito · Banco declinado / barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0066", "Máquina Supino Reto", "Bench press machine", "Foco em peito · Bench press machine. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0068", "One Arm Supino Reto", "Banco reto / halteres", "Foco em peito · Banco reto / halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0069", "Flexão no Bosu", "Bosu ball", "Foco em peito · Bosu ball. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0070", "Supino Solo Unilateral", "Barra", "Foco em peito · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0071", "Crucifixo Unilateral com Halteres", "Banco reto / dumbell", "Foco em peito · Banco reto / dumbell. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0072", "Flexão Unilateral", "Bosu ball", "Foco em peito · Bosu ball. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0076", "Flexão com Pés na Bola", "Peso corporal / bola", "Foco em peito · Peso corporal / bola. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0079", "Pullover Braços Estendidos", "Banco reto / halteres", "Foco em peito · Banco reto / halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0080", "Supino Inclinado com Halteres", "Dumbbells / banco inclinado", "Foco em peito · Dumbbells / banco inclinado. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0081", "Smith Máquina Incline Supino Reto", "Smith machine / banco inclinado", "Foco em peito · Smith machine / banco inclinado. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0082", "Wide Grip Supino Reto", "Banco reto / barra", "Foco em peito · Banco reto / barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0083", "Wide Grip Decline Supino Reto", "Barra / banco declinado", "Foco em peito · Barra / banco declinado. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0085", "Supino Declinado na Máquina", "Chest machine", "Foco em peito · Chest machine. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0086", "Remada Invertida", "Barra", "Foco em peito · Barra. Execução controlada, descida em 2 a 3 segundos."),
      ],
    },
  },
  {
    catId: "triceps",
    sub: {
      id: "triceps-acervo",
      name: "Acervo completo",
      exercises: [
        evkEx("0020", "Press Tate (Tríceps)", "Halteres", "Foco em tríceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0162", "Fundos no Banco", "Peso corporal", "Foco em tríceps · Peso corporal. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0163", "Tríceps Pushdown Inclinado", "Cabo", "Foco em tríceps · Cabo. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0164", "Tríceps Francês Inclinado no Cabo", "Cabo", "Foco em tríceps · Cabo. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0165", "Tríceps Testa no Cabo", "Cabo", "Foco em tríceps · Cabo. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0166", "Tríceps Extensão Unilateral no Cabo", "Cabo", "Foco em tríceps · Cabo. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0168", "Supino Fechado para Tríceps Testa", "Barra", "Foco em tríceps · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0169", "Tríceps Francês Declinado com Halteres", "Halteres", "Foco em tríceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0170", "Tríceps Francês Declinado com Barra W", "Barra", "Foco em tríceps · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0171", "Mergulho na Máquina", "Máquina", "Foco em tríceps · Máquina. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0173", "Tríceps Extensão Unilateral com Halter", "Halteres", "Foco em tríceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0174", "Tríceps Francês Inclinado com Barra", "Barra", "Foco em tríceps · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0175", "JM Press (Tríceps)", "Barra", "Foco em tríceps · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0176", "Tríceps Concentrado de Joelhos no Cabo", "Cabo", "Foco em tríceps · Cabo. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0177", "Kneeling Triceps Extension com Cable", "Cabo", "Foco em tríceps · Cabo. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0178", "Low Triceps Extension com Cable", "Cabo", "Foco em tríceps · Cabo. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0180", "Lying Close Grip Triceps Press to Chin com Barbell", "Barra", "Foco em tríceps · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0181", "Tríceps Extensão Deitado com Halteres", "Halteres", "Foco em tríceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0182", "Tríceps Testa com Halteres", "Halteres", "Foco em tríceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0183", "Supino Fechado com Barra", "Barra", "Foco em tríceps · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0184", "Lying Two Arm Triceps Extension com Dumbbell", "Halteres", "Foco em tríceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0185", "Extensão Reversa Clássica", "Barra", "Foco em tríceps · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0186", "Single Arm Pronated Triceps Extension com Dumbbell", "Halteres", "Foco em tríceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0187", "Single Arm Supinated Triceps Extension com Dumbbell", "Halteres", "Foco em tríceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0188", "Close Triceps Pushup", "Peso corporal", "Foco em tríceps · Peso corporal. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0189", "Tríceps Pulley Supinado", "Cabo", "Foco em tríceps · Cabo. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0190", "Reverse Triceps Supino Reto com Barbell", "Barra", "Foco em tríceps · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0191", "Seated Tríceps Extensão Unilateral com Halter", "Halteres", "Foco em tríceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0192", "Seated Two-Arm Triceps Extension com Dumbbell", "Halteres", "Foco em tríceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0194", "Seated Triceps Press com Dumbbell", "Halteres", "Foco em tríceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0195", "Smith Máquina Close Grip Supino Reto", "Smith machine", "Foco em tríceps · Smith machine. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0196", "Bent-Over Tríceps Extensão Unilateral com Halter", "Halteres", "Foco em tríceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0197", "Bent-Over Two Arm Triceps Extension com Dumbbell", "Halteres", "Foco em tríceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0198", "Tríceps Extensão em Pé", "Halteres", "Foco em tríceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0199", "One Arm Low-Pulley Triceps Extension com Cable", "Cabo", "Foco em tríceps · Cabo. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0201", "Tríceps Francês em Pé com Barra", "Barra", "Foco em tríceps · Barra. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0202", "Tríceps Extensão em Pé com Towel", "Peso corporal", "Foco em tríceps · Peso corporal. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0203", "Press Tate com Dumbbell", "Halteres", "Foco em tríceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0204", "Tríceps Kickback com Halter", "Halteres", "Foco em tríceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0207", "Tríceps Pulley Triângulo", "Cabo / v-bar", "Foco em tríceps · Cabo / v-bar. Execução controlada, descida em 2 a 3 segundos."),
        evkEx("0209", "Tríceps Francês Inclinado com Halteres", "Halteres", "Foco em tríceps · Halteres. Execução controlada, descida em 2 a 3 segundos."),
      ],
    },
  },
];

/** Anexa os subs expandidos às categorias do demoLib (in place). */
export function applyExpandedLibrary(demoLib: DemoCategory[]): void {
  for (const { catId, sub } of EXPANDED_SUBS) {
    const cat = demoLib.find((c) => c.id === catId);
    if (cat) cat.subs.push(sub);
  }
}
