-- =====================================================================
-- 008_seed_all_exercises.sql
-- Seed completo: 286 exercícios da biblioteca (base + acervo)
-- gym_id = NULL (global do produto). Academias podem adicionar próprios.
-- Gerado automaticamente por scripts/gen-exercises-migration.ts
-- =====================================================================

-- Seeds globais (gym_id IS NULL) — só insere se a tabela estiver vazia
-- Não deleta exercícios que tenham FKs (workout_exercises, workout_logs)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.exercises WHERE gym_id IS NULL LIMIT 1) THEN
    INSERT INTO public.exercises (gym_id, name, category, muscles, technique_default, high_impact, tips) VALUES
(null, 'Supino Reto', 'peito', array['peito','triceps','ombro'], 'normal', true, array['Mantenha escápulas retraídas','Barra na linha do mamilo']),
(null, 'Supino Inclinado', 'peito', array['peito','ombro'], 'normal', false, array['Banco a 30-45°','Foco na porção clavicular']),
(null, 'Supino Declinado', 'peito', array['peito'], 'normal', false, array['Banco declinado','Foco na porção esternal']),
(null, 'Supino com Halteres', 'peito', array['peito','triceps'], 'normal', false, array['Maior amplitude','Estabilizadores ativos']),
(null, 'Crucifixo com Halteres', 'peito', array['peito'], 'normal', false, array['Movimento em arco','Contração no topo']),
(null, 'Crucifixo na Polia Baixa', 'peito', array['peito'], 'normal', false, array['Cruze os braços à frente','Leve flexão de cotovelo']),
(null, 'Voador (Peck Deck)', 'peito', array['peito'], 'normal', false, array['Escápulas encostadas','Aproxime os braços']),
(null, 'Flexão de Braço', 'peito', array['peito','core','triceps'], 'normal', true, array['Corpo reto','Cotovelos a 45°']),
(null, 'Fundos (Paralelas)', 'peito', array['peito','triceps'], 'normal', true, array['Corpo vertical','Desça até 90°']),
(null, 'Puxada Alta Aberta', 'costas', array['costas','biceps'], 'normal', false, array['Puxe até a clavícula','Cotovelos para baixo']),
(null, 'Puxada Alta Fechada', 'costas', array['costas','biceps'], 'normal', false, array['Maior ênfase no meio','Bíceps auxilia']),
(null, 'Pulldown Supinado', 'costas', array['costas','biceps'], 'normal', false, array['Empunhadura invertida','Foco na parte baixa']),
(null, 'Puxada com Triângulo', 'costas', array['costas','biceps'], 'normal', false, array['Cotovelos junto ao corpo','Puxe até o esterno']),
(null, 'Barra Fixa', 'costas', array['costas','biceps'], 'normal', true, array['Queixo acima da barra','Negativa se precisar']),
(null, 'Barra Fixa Pronada', 'costas', array['costas','biceps'], 'normal', true, array['Maior ênfase no dorsal','Meio das costas']),
(null, 'Barra Fixa Supinada', 'costas', array['costas','biceps'], 'normal', true, array['Maior ativação de bíceps','Dorsal junto']),
(null, 'Remada Curvada', 'costas', array['costas','biceps'], 'normal', false, array['Tronco a 45°','Puxe ao abdômen']),
(null, 'Remada Baixa (Cabo)', 'costas', array['costas','biceps'], 'normal', false, array['Sentado','Escápulas juntas']),
(null, 'Remada Unilateral', 'costas', array['costas','biceps'], 'normal', false, array['Apoio no banco','Puxe ao quadril']),
(null, 'Remada Cavalinho', 'costas', array['costas','biceps'], 'normal', false, array['Apoio no banco inclinado','Halters ao abdômen']),
(null, 'Remada na Polia Baixa', 'costas', array['costas','biceps'], 'normal', false, array['Puxe ao abdômen','Cotovelos perto do corpo']),
(null, 'Shrugg', 'costas', array['costas'], 'normal', false, array['Eleve os ombros','Segure no topo']),
(null, 'Desenvolvimento Militar', 'ombro', array['ombro','triceps'], 'normal', true, array['Core firme','Sem arco lombar']),
(null, 'Desenvolvimento com Halteres', 'ombro', array['ombro','triceps'], 'normal', false, array['Maior amplitude','Controle cada lado']),
(null, 'Desenvolvimento Arnold', 'ombro', array['ombro','triceps'], 'normal', false, array['Rotação dos punhos','Subida completa']),
(null, 'Elevação Lateral', 'ombro', array['ombro'], 'normal', false, array['Até a linha dos ombros','Cotovelos leves']),
(null, 'Elevação Frontal', 'ombro', array['ombro'], 'normal', false, array['Um braço de cada vez','Até a altura dos olhos']),
(null, 'Elevação Lateral na Polia', 'ombro', array['ombro'], 'normal', false, array['Cotovelo flexionado','Abra lateralmente']),
(null, 'Desenvolvimento na Máquina', 'ombro', array['ombro','triceps'], 'normal', false, array['Movimento guiado','Bom para iniciantes']),
(null, 'Rosca Direta', 'biceps', array['biceps'], 'normal', false, array['Cotovelos fixos','Sem balanço']),
(null, 'Rosca Alternada', 'biceps', array['biceps'], 'normal', false, array['Um braço de cada vez','Controle a descida']),
(null, 'Rosca Scott', 'biceps', array['biceps'], 'normal', false, array['Braços apoiados','Amplitude sem travar']),
(null, 'Rosca Concentrada', 'biceps', array['biceps'], 'normal', false, array['Coxa apoiando cotovelo','Controle total']),
(null, 'Rosca Martelo', 'biceps', array['biceps','panturrilha'], 'normal', false, array['Empunhadura neutra','Braquial e antebraço']),
(null, 'Rosca na Polia Baixa', 'biceps', array['biceps'], 'normal', false, array['Cotovelos fixos','Puxe a barra para cima']),
(null, 'Rosca 21', 'biceps', array['biceps'], 'normal', false, array['7+7+7 repetições','Metade inferior, superior, completa']),
(null, 'Tríceps Pulley', 'triceps', array['triceps'], 'normal', false, array['Cotovelos fixos','Estenda totalmente']),
(null, 'Tríceps Testa', 'triceps', array['triceps'], 'normal', false, array['Deite no banco','Flexione atrás da cabeça']),
(null, 'Tríceps Corda', 'triceps', array['triceps'], 'normal', false, array['Abra as pontas ao final','Cabo com corda']),
(null, 'Tríceps Francês', 'triceps', array['triceps'], 'normal', false, array['Acima da cabeça','Desça atrás da nuca']),
(null, 'Tríceps Máquina', 'triceps', array['triceps'], 'normal', false, array['Movimento guiado','Isolar tríceps']),
(null, 'Mergulho (Paralelas)', 'triceps', array['triceps','peito'], 'normal', true, array['Corpo reto','Cotovelos para trás']),
(null, 'Rosca de Punho', 'biceps', array['biceps'], 'normal', false, array['Antebraços apoiados','Flexione o punho']),
(null, 'Rosca Inversa', 'biceps', array['biceps'], 'normal', false, array['Empunhadura pronada','Movimente os punhos']),
(null, 'Extensão de Punho', 'biceps', array['biceps'], 'normal', false, array['Antebraços apoiados','Estenda os punhos']),
(null, 'Farmer Walk', 'perna', array['perna','biceps'], 'normal', false, array['Halteres pesados','Postura firme']),
(null, 'Agachamento no Smith', 'perna', array['perna','gluteo'], 'normal', false, array['Pés à frente','Coxa paralela']),
(null, 'Agachamento Livre', 'perna', array['perna','gluteo','core'], 'normal', true, array['Barra nas costas','Desça com controle']),
(null, 'Agachamento Frontal', 'perna', array['perna','gluteo'], 'normal', true, array['Barra nos ombros frontais','Core firme']),
(null, 'Agachamento Sumô', 'perna', array['perna','gluteo'], 'normal', false, array['Pés abertos','Ative glúteo e adutores']),
(null, 'Agachamento Búlgaro', 'perna', array['perna','gluteo'], 'normal', false, array['Um pé atrás','Desça com o da frente']),
(null, 'Leg Press 45°', 'perna', array['perna','gluteo'], 'normal', false, array['Pés na largura dos ombros','Lombar colada']),
(null, 'Leg Press Pés Altos', 'perna', array['perna','gluteo'], 'normal', false, array['Maior ênfase posterior','Glúteo ativo']),
(null, 'Leg Press Unilateral', 'perna', array['perna','gluteo'], 'normal', false, array['Uma perna por vez','Corrigir desequilíbrios']),
(null, 'Cadeira Extensora', 'perna', array['perna'], 'normal', false, array['Estenda até travar','Sem soltar o peso']),
(null, 'Afundo', 'perna', array['perna','gluteo'], 'normal', true, array['Passo à frente','Joelho traseiro quase no chão']),
(null, 'Mesa Flexora', 'perna', array['perna','gluteo'], 'normal', false, array['Flexione as pernas','Calcanhar ao glúteo']),
(null, 'Cadeira Flexora', 'perna', array['perna','gluteo'], 'normal', false, array['Movimento guiado','Controle excêntrica']),
(null, 'Stiff', 'perna', array['perna','gluteo','costas'], 'normal', false, array['Quadril para trás','Posterior trabalhando']),
(null, 'Bom Dia', 'perna', array['perna','gluteo','costas'], 'normal', false, array['Barra nas costas','Coluna neutra']),
(null, 'Hiperextensão Lombar', 'perna', array['perna','costas'], 'normal', false, array['Estenda o tronco','Controle no movimento']),
(null, 'Cadeira Abdutora', 'perna', array['perna','gluteo'], 'normal', false, array['Afaste as pernas','Controle a volta']),
(null, 'Elevação Pélvica', 'gluteo', array['gluteo'], 'normal', false, array['Deite de costas','Suba o quadril']),
(null, 'Hip Thrust', 'gluteo', array['gluteo'], 'normal', false, array['Costas no banco','Empurre com glúteos']),
(null, 'Passada', 'perna', array['perna','gluteo'], 'normal', false, array['Passo longo','Empurre pelo calcanhar']),
(null, 'Kickback', 'gluteo', array['gluteo'], 'normal', false, array['Apoie mãos e joelho','Estenda a perna']),
(null, 'Panturrilha em Pé', 'panturrilha', array['panturrilha'], 'normal', false, array['Suba na ponta','Segure 1s no topo']),
(null, 'Panturrilha no Leg Press', 'panturrilha', array['panturrilha'], 'normal', false, array['Pés na ponta','Eleve calcanhares']),
(null, 'Panturrilha Sentado', 'panturrilha', array['panturrilha'], 'normal', false, array['Joelhos a 90°','Eleve calcanhares']),
(null, 'Panturrilha em Pé Unilateral', 'panturrilha', array['panturrilha'], 'normal', false, array['Um pé por vez','Maior amplitude']),
(null, 'Abdominal na Máquina', 'core', array['core'], 'normal', false, array['Encoste na almofada','Sem puxar a cabeça']),
(null, 'Crunch no Solo', 'core', array['core'], 'normal', false, array['Lombar colada','Olhe para o teto']),
(null, 'Crunch na Polia Alta', 'core', array['core'], 'normal', false, array['Puxe a corda','Flexione o tronco']),
(null, 'Prancha Isométrica', 'core', array['core'], 'normal', false, array['Corpo reto','Ative o core']),
(null, 'Prancha com Elevação de Perna', 'core', array['core'], 'normal', false, array['Mantenha a prancha','Eleve uma perna']),
(null, 'Elevação de Perna (Infra)', 'core', array['core'], 'normal', false, array['Pendure-se','Eleve as pernas']),
(null, 'Prancha Lateral', 'core', array['core','ombro'], 'normal', false, array['Apoie o cotovelo','Quadril alinhado']),
(null, 'Russian Twist', 'core', array['core'], 'normal', false, array['Rotação do tronco','Com halter ou peso corporal']),
(null, 'Bicicleta no Solo', 'core', array['core'], 'normal', false, array['Rotação alternada','Cotovelo e joelho oposto']),
(null, 'Mountain Climber', 'core', array['core'], 'normal', true, array['Posição de prancha','Joelhos ao peito']),
(null, 'Esteira', 'cardio', array['cardio'], 'normal', false, array['Aqueça 5 min','Progressão gradual']),
(null, 'Bicicleta Ergométrica', 'cardio', array['cardio'], 'normal', false, array['Cadência constante','Posição confortável']),
(null, 'Elíptico', 'cardio', array['cardio'], 'normal', false, array['Movimento fluido','Resistência progressiva']),
(null, 'Remador', 'cardio', array['cardio','costas'], 'normal', false, array['Empurre com pernas','Sequência puxar-acabar']),
(null, 'Burpee', 'cardio', array['cardio'], 'normal', true, array['Flexão → impulso → salto','Mãos acima da cabeça']),
(null, 'Pular Corda', 'cardio', array['cardio'], 'normal', true, array['Pulos rápidos','Aterrisse suave']),
(null, 'Swing de Kettlebell', 'cardio', array['cardio','gluteo'], 'normal', false, array['Balanço pélvico','Até a altura do peito']),
(null, 'Box Jump', 'cardio', array['cardio','perna'], 'normal', true, array['Salto no box','Amortecimento suave']),
(null, 'Sprint na Esteira', 'cardio', array['cardio'], 'normal', true, array['Corridas curtas','Intervalo de recuperação']),
(null, 'Alongamento de Posterior', 'core', array['perna'], 'normal', false, array['Sentado','Alcance os pés']),
(null, 'Quadril (Borboleta)', 'core', array['perna','gluteo'], 'normal', false, array['Plantas juntas','Puxe calcanhares']),
(null, 'Mobilidade de Ombro', 'ombro', array['ombro'], 'normal', false, array['Gire os braços','Aumente amplitude']),
(null, 'Alongamento de Peito', 'peito', array['peito'], 'normal', false, array['Apoie braço na parede','Rotacione o tronco']),
(null, 'Gato e Vaca', 'core', array['core'], 'normal', false, array['Flexão e extensão lombar','Quadrupedia']),
(null, 'Abdominal Draw In', 'core', array['core'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Bicicleta Air Bike', 'core', array['core'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Ab Rollout com Barra', 'core', array['core'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Ab Rollout de Joelhos com Barra', 'core', array['core'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Elevação de Quadril com Joelhos Dobrados', 'core', array['core'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Abdominal Cruzado', 'core', array['core'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Abdominal com Pés na Bola', 'core', array['core'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Abdominal Declinado', 'core', array['core'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Abdominal Oblíquo Declinado', 'core', array['core'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Flexão Lateral com Halter', 'core', array['core'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Abdominal na Bola', 'core', array['core'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Abdominal com Bola', 'core', array['core'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca Inclinada Alternada com Halteres', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca Inclinada com Barra', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca Martelo na Corda', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca Scott no Cabo', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Close Grip Rosca Direta com Barra W', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca Martelo Cruzada com Halter', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca Drag', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca Direta com Halteres', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Prone Incline Rosca Direta com Halteres', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca Direta com Barra W', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca Martelo com Halteres', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca Inclinada Flexora com Halteres', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca Alta no Cabo', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Incline Inner Rosca Direta com Halteres', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca Deitado no Cabo', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca Deitada Pegada Fechada no Cabo', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca no Banco Alto com Barra', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Lying Supine Rosca Direta com Halteres', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca Scott na Máquina', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca Scott Unilateral com Halter', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca Acima da Cabeça no Cabo', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca Scott Martelo com Halteres', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca Inversa com Anilha', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca Concentrada Pegada Fechada', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca Sentado com Halteres', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca Spider com Barra', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Standing Inner Rosca Direta com Halteres', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca Unilateral no Cabo', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca Unilateral no Banco Inclinado', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca Scott com Halteres', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca Direta Pegada Aberta', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca Zottman com Halteres', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca Zottman Scott com Halteres', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca na Máquina', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca Unilateral com Barra Olímpica', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca Sentado na Bola com Halteres', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca no Agachamento com Halter', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'One Arm Bicep Concentration na Stability Ball', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca com Levantamento Terra', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca com Extensão na Bola', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Afundo com Rosca', 'biceps', array['biceps','perna'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca na Bola com Perna Elevada', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Afundo Frontal com Rosca', 'biceps', array['biceps','perna'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca com Medicine Ball na Bola', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca Equilíbrio Unipodal com Halteres', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rosca em V no Bosu com Halteres', 'biceps', array['biceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Barra Fixa Pegada Aberta Supinada', 'costas', array['costas','biceps'], 'normal', true, array['Execução controlada','Descida em 2-3s']),
(null, 'Pullover (Dorsal)', 'costas', array['costas'], 'normal', false, array['Braços quase estendidos','Foque no dorsal']),
(null, 'Pulldown Braços Estendidos', 'costas', array['costas'], 'normal', false, array['Braços estendidos','Puxe com o dorsal']),
(null, 'Levantamento Terra com Barra', 'costas', array['costas','gluteo','perna'], 'normal', true, array['Coluna neutra','Suba com quadris']),
(null, 'Superman (Costas)', 'costas', array['costas'], 'normal', false, array['Isometria 2-3s no topo','Peso corporal']),
(null, 'Remada Invertida', 'costas', array['costas','biceps'], 'normal', false, array['Corpo alinhado','Puxe peito até barra']),
(null, 'Remada Alta com Barra', 'costas', array['costas','ombro'], 'normal', false, array['Cotovelos altos','Barra junto ao corpo']),
(null, 'Levantamento Terra com Halteres', 'costas', array['costas','gluteo'], 'normal', true, array['Coluna neutra','Quadril para trás']),
(null, 'Pullover Cotovelos Flexionados com Halteres', 'costas', array['costas'], 'normal', false, array['Arco completo','Foque no dorsal']),
(null, 'Pullover Braços Estendidos com Halteres', 'costas', array['costas'], 'normal', false, array['Braços quase estendidos','Arco amplo']),
(null, 'Pullover na Bola com Carga', 'costas', array['costas','core'], 'normal', false, array['Estabilize o core','Arco completo']),
(null, 'Elevação de Pernas no Solo', 'perna', array['perna','core'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Afundo com Halteres', 'perna', array['perna','gluteo'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Flutter Kicks', 'perna', array['perna','core'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Flexora em Pé', 'perna', array['perna'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Agachamento Hack na Máquina', 'perna', array['perna','gluteo'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Agachamento Hack com Barra', 'perna', array['perna','gluteo'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Agachamento Hack no Smith', 'perna', array['perna','gluteo'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Afundo Traseiro com Barra', 'perna', array['perna','gluteo'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Afundo Traseiro com Halteres', 'perna', array['perna','gluteo'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Agachamento com Halteres', 'perna', array['perna','gluteo'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Agachamento Lateral com Barra', 'perna', array['perna','gluteo'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Agachamento no Banco com Barra', 'perna', array['perna','gluteo'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Step Up com Barra', 'perna', array['perna','gluteo'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Adução de Quadril', 'perna', array['perna'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Agachamento no Banco com Halteres', 'perna', array['perna','gluteo'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Step Up com Halteres', 'perna', array['perna','gluteo'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Agachamento Frontal no Banco', 'perna', array['perna','gluteo'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Iron Cross com Dumbbells', 'perna', array['perna'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Jefferson Squats com Barbell', 'perna', array['perna','gluteo'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Leg Press Pegada Fechada', 'perna', array['perna'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Agachamento Deitado', 'perna', array['perna'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Agachamento Hack Pegada Fechada', 'perna', array['perna','gluteo'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Agachamento Fechado com Barra', 'perna', array['perna','gluteo'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Agachamento Unilateral com Barra', 'perna', array['perna','gluteo'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Arranco Unilateral com Barra', 'perna', array['perna','gluteo'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Levantamento Terra Unilateral com Barra', 'perna', array['perna','gluteo'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Agachamento Acima da Cabeça com Barra', 'perna', array['perna','gluteo'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Agachamento Velocidade com Barra', 'perna', array['perna','gluteo'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Cadeira Adutora', 'perna', array['perna'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Agachamento Sissy com Anilha', 'perna', array['perna'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Agachamento Pegada Larga com Barra', 'perna', array['perna','gluteo'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Agachamento Zecher', 'perna', array['perna','gluteo'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Afundo Lateral com Rosca', 'perna', array['perna','gluteo'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Círculos com o Tornozelo', 'perna', array['perna'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Panturrilha Burro', 'panturrilha', array['panturrilha'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Panturrilha Sentado Unilateral com Halter', 'panturrilha', array['panturrilha'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Círculos com o Joelho', 'perna', array['perna'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Panturrilha em Pé com Barra', 'panturrilha', array['panturrilha'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Panturrilha Sentado na Máquina', 'panturrilha', array['panturrilha'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Panturrilha Reversa no Smith', 'panturrilha', array['panturrilha'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Panturrilha em Pé na Máquina', 'panturrilha', array['panturrilha'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Elevação Frontal no Cabo', 'ombro', array['ombro'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Remada Alta no Smith', 'ombro', array['ombro'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Remada Alta no Cabo', 'ombro', array['ombro'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Remada Alta com Halteres', 'ombro', array['ombro'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Círculos na Parede com Bola', 'ombro', array['ombro'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Remada Posterior no Smith', 'ombro', array['ombro','costas'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Elevação Posterior Deitado', 'ombro', array['ombro'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Remada Posterior com Barra', 'ombro', array['ombro','costas'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Elevação Posterior com Cabeça no Banco', 'ombro', array['ombro'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Rotação Interna no Cabo', 'ombro', array['ombro'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Elevação Posterior no Cabo', 'ombro', array['ombro'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Elevação Posterior Unilateral', 'ombro', array['ombro'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Remada Alta Unilateral', 'ombro', array['ombro'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Smith Máquina Encolhimento de Ombros', 'ombro', array['ombro'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Barra Fixa Pegada Neutra', 'ombro', array['ombro','costas'], 'normal', true, array['Execução controlada','Descida em 2-3s']),
(null, 'Pullover na Bola com Carga (Ombro)', 'ombro', array['ombro','costas'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Pullover com Cotovelos Flexionados', 'peito', array['peito','costas'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Dumbbell Pullover com Cotovelos Flexionados', 'peito', array['peito','costas'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Close Grip Barbell Supino Reto', 'peito', array['peito','triceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Decline Dumbbell Supino Reto', 'peito', array['peito'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Decline Crucifixo com Halteres', 'peito', array['peito'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Elevação Frontal com Pullover', 'peito', array['peito','ombro'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Hammer Grip Incline Supino Reto', 'peito', array['peito'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Crucifixo Inclinado no Cabo', 'peito', array['peito'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Dumbbell Incline Supino Reto', 'peito', array['peito'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Incline Crucifixo com Halteres', 'peito', array['peito'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Crucifixo Inclinado com Rotação', 'peito', array['peito'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Pullover Declinado Pegada Aberta', 'peito', array['peito','costas'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Máquina Supino Reto', 'peito', array['peito'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'One Arm Supino Reto', 'peito', array['peito'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Flexão no Bosu', 'peito', array['peito','core'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Supino Solo Unilateral', 'peito', array['peito'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Crucifixo Unilateral com Halteres', 'peito', array['peito'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Flexão Unilateral', 'peito', array['peito','core'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Flexão com Pés na Bola', 'peito', array['peito','core'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Pullover Braços Estendidos', 'peito', array['peito','costas'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Supino Inclinado com Halteres (Acervo)', 'peito', array['peito'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Smith Máquina Incline Supino Reto', 'peito', array['peito'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Wide Grip Supino Reto', 'peito', array['peito'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Wide Grip Decline Supino Reto', 'peito', array['peito'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Supino Declinado na Máquina', 'peito', array['peito'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Remada Invertida (Peito)', 'peito', array['peito','costas'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Press Tate (Tríceps)', 'triceps', array['triceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Fundos no Banco', 'triceps', array['triceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Tríceps Pushdown Inclinado', 'triceps', array['triceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Tríceps Francês Inclinado no Cabo', 'triceps', array['triceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Tríceps Testa no Cabo', 'triceps', array['triceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Tríceps Extensão Unilateral no Cabo', 'triceps', array['triceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Supino Fechado para Tríceps Testa', 'triceps', array['triceps','peito'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Tríceps Francês Declinado com Halteres', 'triceps', array['triceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Tríceps Francês Declinado com Barra W', 'triceps', array['triceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Mergulho na Máquina', 'triceps', array['triceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Tríceps Extensão Unilateral com Halter', 'triceps', array['triceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Tríceps Francês Inclinado com Barra', 'triceps', array['triceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'JM Press (Tríceps)', 'triceps', array['triceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Tríceps Concentrado de Joelhos no Cabo', 'triceps', array['triceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Tríceps Extensão de Joelhos no Cabo', 'triceps', array['triceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Tríceps Extensão Baixa no Cabo', 'triceps', array['triceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Tríceps Supino Pegada Fechada com Barra', 'triceps', array['triceps','peito'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Tríceps Extensão Deitado com Halteres', 'triceps', array['triceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Tríceps Testa com Halteres', 'triceps', array['triceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Supino Fechado com Barra', 'triceps', array['triceps','peito'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Extensão Reversa Clássica', 'triceps', array['triceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Tríceps Extensão Pronada com Halter', 'triceps', array['triceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Tríceps Extensão Supinada com Halter', 'triceps', array['triceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Close Triceps Pushup', 'triceps', array['triceps','peito'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Tríceps Pulley Supinado', 'triceps', array['triceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Reverse Triceps Supino Reto com Barbell', 'triceps', array['triceps','peito'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Seated Tríceps Extensão Unilateral com Halter', 'triceps', array['triceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Tríceps Extensão Sentado com Halteres', 'triceps', array['triceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Tríceps Press Sentado com Halteres', 'triceps', array['triceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Smith Máquina Close Grip Supino Reto', 'triceps', array['triceps','peito'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Bent-Over Tríceps Extensão Unilateral com Halter', 'triceps', array['triceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Tríceps Extensão Inclinado com Halteres', 'triceps', array['triceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Tríceps Extensão em Pé', 'triceps', array['triceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Tríceps Extensão Unilateral na Polia Baixa', 'triceps', array['triceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Tríceps Francês em Pé com Barra', 'triceps', array['triceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Tríceps Extensão em Pé com Towel', 'triceps', array['triceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Press Tate com Dumbbell', 'triceps', array['triceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Tríceps Kickback com Halter', 'triceps', array['triceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Tríceps Pulley Triângulo', 'triceps', array['triceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']),
(null, 'Tríceps Francês Inclinado com Halteres', 'triceps', array['triceps'], 'normal', false, array['Execução controlada','Descida em 2-3s']);
  END IF;
END;
$$;
